public class FirstScreen extends javax.swing.JFrame {
    public Schedule schedule;
    /**
     * Creates new form FirstScreen
     */
    
    Schedule s = new Schedule();
    
    public FirstScreen() {
        initComponents();
        studentPanel.setVisible(false);
        warningLabel.setVisible(false);
        teacherPanel.setVisible(false);
        studentMenu.setVisible(false);
        teacherMenu.setVisible(false);
        SeeVisitingGPStudents.setVisible(false);
        adminPanel.setVisible(false);
        StudentOpenCSV.setVisible(false);
        TeacherOpenCSV.setVisible(false);
        SuccessImport.setVisible(false);
        SelectStudent.setEnabled(true);
        //panels' visibility
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //set student list
        //1. get schedule func
        //2. init schedule class
        //2. 
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstScreenStudent = new javax.swing.JFrame();
        StudentFirstScreen = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        StudentButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        firstPanel = new javax.swing.JPanel();
        AdminButton = new javax.swing.JButton();
        StudentButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        selectText = new javax.swing.JLabel();
        TeacherButton = new javax.swing.JButton();
        studentPanel = new javax.swing.JPanel();
        ProgramTitle = new javax.swing.JLabel();
        SelectStudent = new javax.swing.JComboBox<>(s.getStudentsForCombo());
        SelectText = new javax.swing.JLabel();
        studentMenu = new javax.swing.JPanel();
        prog_title = new javax.swing.JLabel();
        guidingtxt = new javax.swing.JLabel();
        teacher_options = new javax.swing.JComboBox<>();
        chooseTeacherTxt = new javax.swing.JLabel();
        why_teacher_txt = new javax.swing.JTextField();
        explainMovingTxt = new javax.swing.JLabel();
        teacherPanel = new javax.swing.JPanel();
        SelectYourself = new javax.swing.JComboBox<>();
        progTitle = new javax.swing.JLabel();
        selectTxt = new javax.swing.JLabel();
        teacherMenu = new javax.swing.JPanel();
        prog_title_txt = new javax.swing.JLabel();
        seeVisibleGP = new javax.swing.JButton();
        manageAssignedGP = new javax.swing.JButton();
        SeeVisitingGPStudents = new javax.swing.JPanel();
        program_txt_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        enter_capacity = new javax.swing.JTextField();
        set_capacity_txt = new javax.swing.JLabel();
        SeeAssignedGPStudents = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        selectingAdminOption = new javax.swing.JLabel();
        importTeachers = new javax.swing.JButton();
        importStudents = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        TeacherOpenCSV = new javax.swing.JPanel();
        TeacherFileChooser = new javax.swing.JFileChooser();
        StudentOpenCSV = new javax.swing.JPanel();
        StudentFileChooser = new javax.swing.JFileChooser();
        SuccessImport = new javax.swing.JPanel();
        SuccessImportTxt = new javax.swing.JLabel();
        GoHomeScreen = new javax.swing.JButton();

        javax.swing.GroupLayout FirstScreenStudentLayout = new javax.swing.GroupLayout(FirstScreenStudent.getContentPane());
        FirstScreenStudent.getContentPane().setLayout(FirstScreenStudentLayout);
        FirstScreenStudentLayout.setHorizontalGroup(
            FirstScreenStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FirstScreenStudentLayout.setVerticalGroup(
            FirstScreenStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout StudentFirstScreenLayout = new javax.swing.GroupLayout(StudentFirstScreen.getContentPane());
        StudentFirstScreen.getContentPane().setLayout(StudentFirstScreenLayout);
        StudentFirstScreenLayout.setHorizontalGroup(
            StudentFirstScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        StudentFirstScreenLayout.setVerticalGroup(
            StudentFirstScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel5.setText("Select Yourself:");

        StudentButton1.setText("Student");
        StudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminButton.setText("Admin");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        StudentButton.setText("Student");
        StudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButtonActionPerformed(evt);
            }
        });

        title.setText("GP Schedule System");

        selectText.setText("Select Yourself:");

        TeacherButton.setText("Teacher");
        TeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
        firstPanel.setLayout(firstPanelLayout);
        firstPanelLayout.setHorizontalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(selectText))
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(firstPanelLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(title)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        firstPanelLayout.setVerticalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(selectText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(AdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(firstPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );

        ProgramTitle.setText("GP Schedule System - Student Home Screen");

        SelectStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectStudentActionPerformed(evt);
            }
        });

        SelectText.setText("Select Yourself:");

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(ProgramTitle)
                .addGap(59, 59, 59))
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(SelectText)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(SelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProgramTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectText)
                .addGap(18, 18, 18)
                .addComponent(SelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        prog_title.setText("GP Schedule System");

        guidingtxt.setText("If moving GPs:");

        teacher_options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Teacher", "Teacher 1", "Teacher 2", "Teacher 3", "Teacher 4" }));

        chooseTeacherTxt.setText("Choose the GP teacher");

        why_teacher_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                why_teacher_txtActionPerformed(evt);
            }
        });

        explainMovingTxt.setText("Tell the teacher why you are coming");

        javax.swing.GroupLayout studentMenuLayout = new javax.swing.GroupLayout(studentMenu);
        studentMenu.setLayout(studentMenuLayout);
        studentMenuLayout.setHorizontalGroup(
            studentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentMenuLayout.createSequentialGroup()
                .addGroup(studentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentMenuLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(prog_title))
                    .addGroup(studentMenuLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(guidingtxt))
                    .addGroup(studentMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(studentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(studentMenuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(why_teacher_txt))
                            .addComponent(teacher_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(studentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(explainMovingTxt)
                            .addComponent(chooseTeacherTxt))))
                .addGap(44, 44, 44))
        );
        studentMenuLayout.setVerticalGroup(
            studentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prog_title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guidingtxt)
                .addGap(41, 41, 41)
                .addGroup(studentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseTeacherTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(why_teacher_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(explainMovingTxt))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        SelectYourself.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher 1", "Teacher 2", "Teacher 3", "Teacher 4", "Teacher 5" }));
        SelectYourself.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectYourselfActionPerformed(evt);
            }
        });

        progTitle.setText("GP Schedule System - Teacher Home Screen");

        selectTxt.setText("Select Yourself:");

        javax.swing.GroupLayout teacherPanelLayout = new javax.swing.GroupLayout(teacherPanel);
        teacherPanel.setLayout(teacherPanelLayout);
        teacherPanelLayout.setHorizontalGroup(
            teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SelectYourself, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(teacherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(teacherPanelLayout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(selectTxt)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );
        teacherPanelLayout.setVerticalGroup(
            teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(SelectYourself, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(teacherPanelLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(selectTxt)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        prog_title_txt.setText("GP Schedule System");

        seeVisibleGP.setText("Manage Coming to GP");
        seeVisibleGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeVisibleGPActionPerformed(evt);
            }
        });

        manageAssignedGP.setText("Manage Assigned GP Students");

        javax.swing.GroupLayout teacherMenuLayout = new javax.swing.GroupLayout(teacherMenu);
        teacherMenu.setLayout(teacherMenuLayout);
        teacherMenuLayout.setHorizontalGroup(
            teacherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherMenuLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(prog_title_txt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherMenuLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(teacherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seeVisibleGP, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageAssignedGP, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        teacherMenuLayout.setVerticalGroup(
            teacherMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prog_title_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(manageAssignedGP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seeVisibleGP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        program_txt_title.setText("GP Schedule System");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "VStudent1", "VStudent 2", "VStudent 3", "VStudent 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("List of Reasons");

        jLabel3.setText("List of Visiting Students");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Reason 1", "Reason 2", "Reason 3", "Reason 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel4.setText("Verify Presence");

        jCheckBox2.setText("VStudent2");

        jCheckBox3.setText("VStudent1");

        jCheckBox1.setText("VStudent3");

        jCheckBox4.setText("VStudent4");

        jCheckBox5.setText("VStudent5");

        enter_capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_capacityActionPerformed(evt);
            }
        });

        set_capacity_txt.setText("Set Max Number of Visiting Students");

        javax.swing.GroupLayout SeeVisitingGPStudentsLayout = new javax.swing.GroupLayout(SeeVisitingGPStudents);
        SeeVisitingGPStudents.setLayout(SeeVisitingGPStudentsLayout);
        SeeVisitingGPStudentsLayout.setHorizontalGroup(
            SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeeVisitingGPStudentsLayout.createSequentialGroup()
                .addGroup(SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeeVisitingGPStudentsLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(program_txt_title))
                    .addGroup(SeeVisitingGPStudentsLayout.createSequentialGroup()
                        .addGroup(SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeeVisitingGPStudentsLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeeVisitingGPStudentsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(set_capacity_txt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enter_capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBox3)
                                .addComponent(jCheckBox2)
                                .addComponent(jCheckBox1)
                                .addComponent(jCheckBox4)
                                .addComponent(jCheckBox5)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SeeVisitingGPStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addGap(15, 15, 15))
        );
        SeeVisitingGPStudentsLayout.setVerticalGroup(
            SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeeVisitingGPStudentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(program_txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SeeVisitingGPStudentsLayout.createSequentialGroup()
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(SeeVisitingGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter_capacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set_capacity_txt))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout SeeAssignedGPStudentsLayout = new javax.swing.GroupLayout(SeeAssignedGPStudents);
        SeeAssignedGPStudents.setLayout(SeeAssignedGPStudentsLayout);
        SeeAssignedGPStudentsLayout.setHorizontalGroup(
            SeeAssignedGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        SeeAssignedGPStudentsLayout.setVerticalGroup(
            SeeAssignedGPStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        selectingAdminOption.setText("Select one of the options:");

        importTeachers.setText("import teachers");
        importTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importTeachersActionPerformed(evt);
            }
        });

        importStudents.setText("import students");
        importStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importStudentsActionPerformed(evt);
            }
        });

        jLabel2.setText("enter a CSV with name, ID, and teacher");

        jLabel6.setText("enter a CSV with name and ID");

        warningLabel.setText("teacher list is empty - please enter teachers before students");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(selectingAdminOption, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(warningLabel))
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(importTeachers)
                                    .addComponent(importStudents))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectingAdminOption, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importTeachers)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importStudents)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TeacherFileChooser.setApproveButtonText("");
        TeacherFileChooser.setApproveButtonToolTipText("");
        TeacherFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeacherOpenCSVLayout = new javax.swing.GroupLayout(TeacherOpenCSV);
        TeacherOpenCSV.setLayout(TeacherOpenCSVLayout);
        TeacherOpenCSVLayout.setHorizontalGroup(
            TeacherOpenCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherOpenCSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TeacherFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TeacherOpenCSVLayout.setVerticalGroup(
            TeacherOpenCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherOpenCSVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TeacherFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        StudentFileChooser.setApproveButtonText("");
        StudentFileChooser.setApproveButtonToolTipText("");
        StudentFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentOpenCSVLayout = new javax.swing.GroupLayout(StudentOpenCSV);
        StudentOpenCSV.setLayout(StudentOpenCSVLayout);
        StudentOpenCSVLayout.setHorizontalGroup(
            StudentOpenCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentOpenCSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        StudentOpenCSVLayout.setVerticalGroup(
            StudentOpenCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentOpenCSVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StudentFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SuccessImportTxt.setText("You have successfully imported!");

        GoHomeScreen.setText("Go to Home Screen");
        GoHomeScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoHomeScreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuccessImportLayout = new javax.swing.GroupLayout(SuccessImport);
        SuccessImport.setLayout(SuccessImportLayout);
        SuccessImportLayout.setHorizontalGroup(
            SuccessImportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuccessImportLayout.createSequentialGroup()
                .addGroup(SuccessImportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SuccessImportLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(SuccessImportTxt))
                    .addGroup(SuccessImportLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(GoHomeScreen)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        SuccessImportLayout.setVerticalGroup(
            SuccessImportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuccessImportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SuccessImportTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(GoHomeScreen))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(firstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(399, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(teacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(studentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(teacherMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SeeVisitingGPStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentOpenCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TeacherOpenCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SeeAssignedGPStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SuccessImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(teacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(studentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(teacherMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SeeVisitingGPStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(StudentOpenCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TeacherOpenCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SeeAssignedGPStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SuccessImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void StudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButtonActionPerformed
        firstPanel.setVisible(false);
        studentPanel.setVisible(true);
    }//GEN-LAST:event_StudentButtonActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        firstPanel.setVisible(false);
        adminPanel.setVisible(true);
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void SelectYourselfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectYourselfActionPerformed
        teacherPanel.setVisible(false);
        teacherMenu.setVisible(true);
    }//GEN-LAST:event_SelectYourselfActionPerformed

    private void SelectStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectStudentActionPerformed
        //System.out.println(SelectStudent.getSelectedItem());
        studentPanel.setVisible(false);
        //need to test if student able to move (or if GP frozen)
        studentMenu.setVisible(true);
    }//GEN-LAST:event_SelectStudentActionPerformed

    private void why_teacher_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_why_teacher_txtActionPerformed

        String text = why_teacher_txt.getText();
        String teacher_chosen = (String)teacher_options.getSelectedItem();
        //System.out.println(text);
        //System.out.println(teacher_chosen);
    }//GEN-LAST:event_why_teacher_txtActionPerformed

    private void enter_capacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_capacityActionPerformed
        
        int capacity = Integer.parseInt(enter_capacity.getText());
        System.out.println(capacity);
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_capacityActionPerformed

    private void seeVisibleGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeVisibleGPActionPerformed
        teacherMenu.setVisible(false);
        SeeVisitingGPStudents.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_seeVisibleGPActionPerformed

    private void StudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButton1ActionPerformed
        //show option to import CSV
        //maybe do it so students & teachers on same frame
        //import CSV
        //parse CSV for name & ID

    }//GEN-LAST:event_StudentButton1ActionPerformed

    private void TeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonActionPerformed
        firstPanel.setVisible(false);
        teacherPanel.setVisible(true);
    }//GEN-LAST:event_TeacherButtonActionPerformed

    private void importStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importStudentsActionPerformed
        if (s.getTeachers() == null)
        {
            warningLabel.setVisible(true);
        }
        else
        {
            adminPanel.setVisible(false);
            StudentOpenCSV.setVisible(true);
        }
    }//GEN-LAST:event_importStudentsActionPerformed

    private void importTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importTeachersActionPerformed
        adminPanel.setVisible(false);
        TeacherOpenCSV.setVisible(true);
    }//GEN-LAST:event_importTeachersActionPerformed

    private void StudentFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentFileChooserActionPerformed
        StudentOpenCSV.setVisible(false);

        if(evt.getActionCommand().equals("CancelSelection"))
        {
            adminPanel.setVisible(true);
        }
        else if(evt.getActionCommand().equals("ApproveSelection"))
        {

            PersonLinkedList students = new PersonLinkedList(); //set this to sample test case
            students.add(new Student(104,"Katie", 90));
            students.add(new Student(104, "Jessica", 80));
            s.setStudents(students);
            SelectStudent = javax.swing.JComboBox<>(s.getStudentsForCombo());
            //set JComboBox with students' names
            
            //loop through CSV rows (get # rows as four loop bounds)
            
            //STEPS:
            //1. get file & check if CSV format
            //2. parse file for stuff - should prob know if teach or student
            //3. populate respective LLs
            
            SuccessImport.setVisible(true);

        }
    }//GEN-LAST:event_StudentFileChooserActionPerformed

    private void TeacherFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherFileChooserActionPerformed
        TeacherOpenCSV.setVisible(false);
        
        if(evt.getActionCommand().equals("CancelSelection"))
        {
            adminPanel.setVisible(true);
        }
        else if(evt.getActionCommand().equals("ApproveSelection"))
        {
            //STEPS:
            //1. get file & check if CSV format
            //2. parse file for stuff - should prob know if teach or student
            //3. populate respective LLs
            
            //testCASE
            
            PersonLinkedList teachers = new PersonLinkedList();
            //test case b4 CSV importing works
            teachers.add(new Teacher("Mrs. Smith", 90));
            teachers.add(new Teacher("Mrs. Banks", 80));
            s.setTeachers(teachers);
            warningLabel.setVisible(false);
            SuccessImport.setVisible(true);
        }
    }//GEN-LAST:event_TeacherFileChooserActionPerformed

    private void GoHomeScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoHomeScreenActionPerformed
        SuccessImport.setVisible(false);
        firstPanel.setVisible(true);
    }//GEN-LAST:event_GoHomeScreenActionPerformed
                                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JFrame FirstScreenStudent;
    private javax.swing.JButton GoHomeScreen;
    private javax.swing.JLabel ProgramTitle;
    private javax.swing.JPanel SeeAssignedGPStudents;
    private javax.swing.JPanel SeeVisitingGPStudents;
    private javax.swing.JComboBox<String> SelectStudent;
    private javax.swing.JLabel SelectText;
    private javax.swing.JComboBox<String> SelectYourself;
    private javax.swing.JButton StudentButton;
    private javax.swing.JButton StudentButton1;
    private javax.swing.JFileChooser StudentFileChooser;
    private javax.swing.JFrame StudentFirstScreen;
    private javax.swing.JPanel StudentOpenCSV;
    private javax.swing.JPanel SuccessImport;
    private javax.swing.JLabel SuccessImportTxt;
    private javax.swing.JButton TeacherButton;
    private javax.swing.JFileChooser TeacherFileChooser;
    private javax.swing.JPanel TeacherOpenCSV;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel chooseTeacherTxt;
    private javax.swing.JTextField enter_capacity;
    private javax.swing.JLabel explainMovingTxt;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JLabel guidingtxt;
    private javax.swing.JButton importStudents;
    private javax.swing.JButton importTeachers;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton manageAssignedGP;
    private javax.swing.JLabel progTitle;
    private javax.swing.JLabel prog_title;
    private javax.swing.JLabel prog_title_txt;
    private javax.swing.JLabel program_txt_title;
    private javax.swing.JButton seeVisibleGP;
    private javax.swing.JLabel selectText;
    private javax.swing.JLabel selectTxt;
    private javax.swing.JLabel selectingAdminOption;
    private javax.swing.JLabel set_capacity_txt;
    private javax.swing.JPanel studentMenu;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JPanel teacherMenu;
    private javax.swing.JPanel teacherPanel;
    private javax.swing.JComboBox<String> teacher_options;
    private javax.swing.JLabel title;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JTextField why_teacher_txt;
    // End of variables declaration//GEN-END:variables
}
